# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170404_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chat'),
        ),
    ]
