# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20170404_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
