# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170404_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
