# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170407_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ja_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
